Added responsiveness for all the screens
WintrCat/freechess pull request #44
Opened 2024-05-03 08:49 UTC by Razen04

I have added responsiveness for all the screen size and all fixed the evaluation bar which was not working before for mobile screen sizes.

2024-05-04 21:59 UTC, WintrCat requested changes
thanks for the PR :) i've given you a code review - there are some changes that need implementing before we can proceed with the merge.

Besides the comments in the code review, there is was additional bug I found - between screen widths of 430 through 960 pixels, the responsiveness of the board breaks down. This will need fixing before merging. I've attached a screenshot of it:
![image](https://github.com/WintrCat/freechess/assets/89023414/2dd34829-35f7-46c7-a3cc-31c525da9062)

2024-05-04 21:59 UTC, WintrCat commented on nodemon.json
remove public from the watch list, it is inside src so changes to public will be watched anyway

2024-05-04 21:59 UTC, WintrCat commented on src/public/global.css
code smell: there should be a space between CSS properties and values

2024-05-04 21:59 UTC, WintrCat commented on src/public/pages/report/styles/index.css
code smells: there should always be a space between the CSS selector and the `{`.

2024-05-04 21:59 UTC, WintrCat commented on src/public/pages/report/styles/index.css
> +@media only screen and (max-width: 1536px){
here is an example of said code smell

2024-05-04 21:59 UTC, WintrCat commented on src/public/pages/report/styles/index.css
> +    #classification-message-container{
and a second example

2024-05-04 21:59 UTC, WintrCat commented on src/public/pages/report/styles/reviewpanel.css
code smells: there should always be a space between the CSS selector and the `{`.

2024-05-04 21:59 UTC, WintrCat commented on src/public/pages/report/styles/reviewpanel.css
> +.depthTitle{
an example of said code smell

2024-05-06 13:33 UTC, Razen04 commented
I have fixed the said issues, you can check it.

2024-05-06 13:52 UTC, Razen04 commented
I also fixed a small problem of arrow functioning from Issue #37.

2024-05-06 14:45 UTC, WintrCat requested changes
Thanks for your updates :)

The code for the game selection arrows breaks down as soon as the user flips to a page in a different year, which needs to be addressed. From a quick glance it looks like you need to update some of the if-statements. Code smells were resolved, although the evaluation bar is still distorted when the height of the board decreases.

![image](https://github.com/WintrCat/freechess/assets/89023414/4bdd8756-4d7a-4aab-96d6-e7b9ca096575)

2024-05-06 14:45 UTC, WintrCat commented on src/public/pages/report/scripts/loadgame.ts
This code does not work - the dialog breaks down completely if the user switches pages to a different year.

2024-05-06 15:05 UTC, Razen04 commented
> the evaluation bar is still distorted when the height of the board decreases

Do you mean the edges and of bar and the number in it? 

For the edges I can just remove the border radius and for number I don't if it is can be fixed using CSS. If there is something else you mean you can let me know and I will fix it.

For the date I didn't see the year changing problem while checking so I will se if I can fix it or not.

2024-05-12 11:11 UTC, WintrCat reviewed
Thanks for this :)

The game selection date issue was fixed with your commit, although as I have said we aren't able to merge anything without the evaluation number issue being fixed. It is still distorted on smaller screen widths. The evaluation bar itself is an HTML canvas, so I believe changing the height CSS property of it will distort its contents. You may have to change the height of the canvas internally, which means you may have to change the JS implementation such that it updates itself in accordance to the page width. I'm not 100% sure though, I would guess there has to be some cleaner way to get this done.

2024-05-12 11:11 UTC, WintrCat commented on src/public/pages/report/scripts/loadgame.ts
> +        if (gamesPeriod.month == 12 && (gamesPeriod.year) >= new Date().getFullYear()) {
code smell: brackets around gamesPeriod.year are not needed when there is no subtraction

2024-05-13 14:54 UTC, Razen04 commented
Fixed the distortion using SVG as they are easy to scale down for smaller screens without any distortions. I had to change the eval bar script for this to work with SVG instead of HTML Canvas.

2024-05-14 20:33 UTC, WintrCat approved these changes
thank you :)

2024-05-14 20:34 UTC, merged