feat: add classification count for analysis
WintrCat/freechess pull request #47
Opened 2024-05-16 08:27 UTC by Kinggodhoon

Feature addition to show engine evaluations.

I'm a backend developer, so the front-end code is a bit messy, but I did my best.
If you have any corrections or improvements, please leave a comment.

Thank you.

<img width="417" alt="image" src="https://github.com/WintrCat/freechess/assets/50986866/fa177104-67e4-410e-ae20-52f10d0187a5">
<img width="1281" alt="image" src="https://github.com/WintrCat/freechess/assets/50986866/0dc40f19-865f-4ee5-a4ae-21b9fe373662">
<img width="1725" alt="image" src="https://github.com/WintrCat/freechess/assets/50986866/dc67c46e-25c1-4f60-8cae-029341326d8b">

2024-05-16 11:44 UTC, WintrCat commented
Thank you :) This is great! Only thing that needs doing is the responsiveness, since the design breaks down at smaller and mobile screen sizes:
![image](https://github.com/WintrCat/freechess/assets/89023414/d35e2d45-a58e-4396-ad87-9e4db1e1c8d8)

Though, I will admit the frontend code is not fantastic - there may be work on an overhaul at some point.

2024-05-16 12:42 UTC, tissatussa commented
very nice addition .. a simply big improvement of this yet great web-app !

btw.
i guess the freechessextra version will soon be updated accordingly ?
at this moment this version has higher max depth, could you also adjust this ? - seems a simple fix to me..

2024-05-17 01:32 UTC, superhoonz commented
thank you for your comment
I'll work on it and commit asap :)

2024-05-17 01:51 UTC, superhoonz commented
> Thank you :) This is great! Only thing that needs doing is the responsiveness, since the design breaks down at smaller and mobile screen sizes: ![image](https://private-user-images.githubusercontent.com/89023414/331188908-d35e2d45-a58e-4396-ad87-9e4db1e1c8d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTA1MTksIm5iZiI6MTcxNTkxMDIxOSwicGF0aCI6Ii84OTAyMzQxNC8zMzExODg5MDgtZDM1ZTJkNDUtYTU4ZS00Mzk2LWFkODctOWU0ZGIxZTFjOGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDAxNDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YWUwMDA4MDhiMGE4MmQwZDAyMTQyODY1YzkxOGJmZmJlMmYxMDZiMjdmZTQzZTVkN2I0M2U5YWIxNDBhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P65QdsN833PMWWgKFxgre9t6XTxc8sx9mB-u3CAyRhA)
> 
> Though, I will admit the frontend code is not fantastic - there may be work on an overhaul at some point.

I think add the scroll bar at the side analytics section is the best,
how do you think this idea?

or mouse hover to display small window?, 
like a help messages, tooltips something.

2024-05-17 01:53 UTC, Kinggodhoon commented
> Thank you :) This is great! Only thing that needs doing is the responsiveness, since the design breaks down at smaller and mobile screen sizes: ![image](https://private-user-images.githubusercontent.com/89023414/331188908-d35e2d45-a58e-4396-ad87-9e4db1e1c8d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTEwODMsIm5iZiI6MTcxNTkxMDc4MywicGF0aCI6Ii84OTAyMzQxNC8zMzExODg5MDgtZDM1ZTJkNDUtYTU4ZS00Mzk2LWFkODctOWU0ZGIxZTFjOGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDAxNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMDgwM2NhMDIzNDE3MmJhMjA2OGViM2Y3YWU5YjYxYWI3ZWY4NjY1YTI3YTIxNmRkZDI2MmZhZGUwODk2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HvnHyPrZWUMA3Alt_5mqEBGU_q5N2iayFXYzjoHLgZs)
> 
> Though, I will admit the frontend code is not fantastic - there may be work on an overhaul at some point.

I think add the scroll bar at the side analytics section is the best,
how do you think this idea?

or mouse hover to display small window?,
like a help messages, tooltips something.

2024-05-17 06:44 UTC, Kinggodhoon commented
@WintrCat 
I tried my best 
![화면-기록-2024-05-17-오후-3 39 23](https://github.com/WintrCat/freechess/assets/50986866/185f70bc-e592-4f8a-87ba-82e215832519)

2024-05-17 07:00 UTC, Kinggodhoon commented
> @Kinggodhoon if you're able to implement a scrollbar that would be fantastic :) that's something that has needed adding for a while. thank you so much for your efforts!

Working with scrollbars doesn't seem like it's going to be easy right away.
What about the tooltip-shaped window I just committed?

2024-05-17 09:04 UTC, WintrCat commented
Okay, it's no worries then, we can go with the tooltip :)

Just a nit pick here, do you think you could change the text to "See your classifications"? 

Besides that, I think the only thing you may want to consider is mobile. I think it could be useful to have some sort of hover effect on the text just so that mobile users can be sure that the text has reacted to being pressed, since they would have to click on it for the classifications to appear.

Thanks!

2024-05-17 09:28 UTC, Kinggodhoon commented
> Okay, it's no worries then, we can go with the tooltip :)
> 
> Just a nit pick here, do you think you could change the text to "See your classifications"?
> 
> Besides that, I think the only thing you may want to consider is mobile. I think it could be useful to have some sort of hover effect on the text just so that mobile users can be sure that the text has reacted to being pressed, since they would have to click on it for the classifications to appear.
> 
> Thanks!

@WintrCat 
maybe it can be nice small things

i added the small animation on classification-count-tooltip-message

![화면-기록-2024-05-17-오후-6 24 37](https://github.com/WintrCat/freechess/assets/50986866/77df3df4-202e-444a-a629-f35d2a7e7290)

2024-05-17 10:38 UTC, WintrCat requested changes
thanks for this. Some small code style changes need to made, and a tiny bug needs fixing, but then we can proceed with merging. I have left in my review comment a suggested fix to the bug 👍

2024-05-17 10:38 UTC, WintrCat commented on src/public/pages/report/styles/report.css
> +.classification-count-content>img {
there should be whitespace around `>`

e.g `.classification-count-content > img`

2024-05-17 10:38 UTC, WintrCat commented on src/public/pages/report/styles/report.css
> +#classification-count-tooltip-message:hover+#classification-count-container {
there should be whitespace around `+`

2024-05-17 10:38 UTC, WintrCat commented on src/public/pages/report/styles/report.css
> +    transition: color 0.25s ease-in-out;
CSS `transition` property should not be in the `:hover` selector. I suggest adding another CSS rule
```css
#classification-count-tooltip-message {
    transition: color 0.25s ease-in-out;
}
```
somewhere, otherwise the highlight snaps to disabled when the mouse leaves the text.

2024-05-17 12:13 UTC, Kinggodhoon commented on src/public/pages/report/styles/report.css
> +    transition: color 0.25s ease-in-out;
It was my intention that it would only be highlighted when the mouse is hovering.
My English is a weak so maybe I'm not understanding it well,

so you want it will be start continue to highlight like pulse, when once the mouse hover the message ?

Sorry to bother you

2024-05-17 13:10 UTC, WintrCat commented
No worries mate, I've gone ahead and implemented these things myself

2024-05-17 13:11 UTC, WintrCat approved these changes

2024-05-17 13:11 UTC, merged

2024-05-17 14:13 UTC, Kinggodhoon commented
oh thank you
If i have a new idea, i will PR it again